// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLD6qVz_5aM4gIv37z3WxoYReOYPscF_g',
    appId: '1:173438573290:web:8396fb57e1dd4e56645593',
    messagingSenderId: '173438573290',
    projectId: 'mynotes-flutter-b37a9',
    authDomain: 'mynotes-flutter-b37a9.firebaseapp.com',
    storageBucket: 'mynotes-flutter-b37a9.appspot.com',
    measurementId: 'G-W92D1179D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgKE0TzR7RyQtwB_Apnv-P6anCeHJUA6E',
    appId: '1:173438573290:android:4bd3f3f8a8fbde04645593',
    messagingSenderId: '173438573290',
    projectId: 'mynotes-flutter-b37a9',
    storageBucket: 'mynotes-flutter-b37a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxd-E0bxku1pCABmOyAoUwE0l6fSL3Jg',
    appId: '1:173438573290:ios:d735ff5703eab0e5645593',
    messagingSenderId: '173438573290',
    projectId: 'mynotes-flutter-b37a9',
    storageBucket: 'mynotes-flutter-b37a9.appspot.com',
    iosClientId: '173438573290-f9ldqbgfpaan96q6k4489kbcp0ifkdrn.apps.googleusercontent.com',
    iosBundleId: 'no.thanh.mynotes',
  );
}
